(source "gnu")
(source "melpa")

(package "flycheck-google-cpplint" "1.0.2" "Help to comply with the Google C++ Style Guide")

(package-file "flycheck-google-cpplint.el")

(depends-on "emacs" "24.3")
(depends-on "flycheck")
(depends-on "dash")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
